---
title: "7/25 Heatmap"
author: "Hyunsu Lee"
date: "July 25, 2016"
output: html_document
---

```{r, echo = FALSE, include = FALSE}
# Data load & library load
require(reshape2)
require(gplots)
require(preprocessCore)
require(RColorBrewer)
require(ggplot2)

DCT <- read.csv("DEG_DCT.csv", header = TRUE)
EAR <- read.csv("DEG_ear.csv", header = TRUE)
LC <- read.csv("DEG_LC.csv", header = TRUE)
```


```{r, echo=FALSE, include=FALSE}
## Definefunction 
RNAseq <- function(x_data){
  require(preprocessCore)
  x_mat <-as.matrix(x_data[2:8])
  x_mat = x_mat + 1
  x_mat_log = log10(x_mat)
  #x_mat_log_nq = normalize.quantiles(x_mat_log)
  #colnames(x_mat_log_nq) <- colnames(x_mat_log)
  rownames(x_mat_log) <- t(x_data[1])
  return(x_mat_log)
}

```



```{r, echo=FALSE, include = FALSE}
## data process
#RNAseq.R function, matrix conversion, log10, do not normalize quantile.
DCT_m <- RNAseq(DCT)
EAR_m <- RNAseq(EAR)
LC_m <- RNAseq(LC)
'''
attach(DCT)
DCT_m_sorted <- RNAseq(DCT[order(-DCT1, -DCT2),])

attach(EAR)
EAR_m_sorted <- RNAseq(EAR[order(-ERST2, -ERST3),])

attach(LC)
LC_m_sorted <- RNAseq(LC[order(-LC1, -LC2, -LC3),])
'''
```


```{r, echo=FALSE, include = FALSE}
## distance correlation
corDist_DCT <- dist(DCT_m)
corDist_EAR <- dist(EAR_m)
corDist_LC <- dist(LC_m)

hCluCOM_DCT <-hclust(corDist_DCT, method = "complete")
hCluCOM_EAR <-hclust(corDist_EAR, method = "complete")
hCluCOM_LC <-hclust(corDist_LC, method = "complete")

cluCOM_dend_DCT <- as.dendrogram(hCluCOM_DCT)
cluCOM_dend_EAR <- as.dendrogram(hCluCOM_EAR)
cluCOM_dend_LC <- as.dendrogram(hCluCOM_LC)
```


## hierachical clustering(3 plot)
   DCT signature
```{r, echo=FALSE}
r <- colorRampPalette(c("firebrick2", "lightgoldenrodyellow", "darkolivegreen4"))(n = 299)
# r <- colorRampPalette(c("firebrick2", "lightgoldenrodyellow", "green"))(n = 299)

rBr <- brewer.pal(11, "RdYlGn")

tiff(filename = "DCT.tif", width = 5, height = 7, units = "in", res=300)
heatmap.2(DCT_m, col=r, scale = "row", cexCol = 1, labRow = NA, key = TRUE, keysize = 1.5, trace = "none", density.info = "none", dendrogram = "none", Rowv=cluCOM_dend_DCT, Colv = FALSE)
 
```

   ear signature
```{r, echo=FALSE}
tiff(filename = "ear.tif", width = 5, height = 7, units = "in", res=300)
heatmap.2(EAR_m, col=r, scale = "row", cexCol = 1, labRow = NA, key = TRUE,keysize = 1.5, trace = "none", density.info = "none", dendrogram = "none", Rowv=cluCOM_dend_EAR, Colv = FALSE)
```

   LC signature
```{r, echo=FALSE}
tiff(filename = "LC.tif", width = 5, height = 7, units = "in", res=300)
heatmap.2(LC_m, col=r, scale = "row", cexCol = 1, labRow = NA, key = TRUE, keysize = 1.5, trace = "none", density.info = "none", dendrogram = "none", Rowv=cluCOM_dend_LC, Colv = FALSE)
```

## Sorted version(6 plot)
### Scaling by row
   DCT signature
```{r, echo=FALSE}
heatmap.2(DCT_m_sorted, col=rBr, scale = "row", cexCol = 1, labRow = NA, key = TRUE, trace = "none", density.info = "none", dendrogram = "none", Rowv = "none", Colv = "none")
```

   ear signature
```{r, echo=FALSE}
heatmap.2(EAR_m_sorted, col=rBr, scale = "row", cexCol = 1, labRow = NA, key = TRUE, trace = "none", density.info = "none", dendrogram = "none", Rowv = "none", Colv = "none")
```

   LC signature
```{r, echo=FALSE}
heatmap.2(LC_m_sorted, col=rBr, scale = "row", cexCol = 1, labRow = NA, key = TRUE, trace = "none", density.info = "none", dendrogram = "none", Rowv = "none", Colv = "none")
```

### Scaling by column
   DCT signature
```{r, echo=FALSE}
heatmap.2(DCT_m_sorted, col=r, scale = "col", cexCol = 1, labRow = NA, key = TRUE, trace = "none", density.info = "none", dendrogram = "none", Rowv = "none", Colv = "none")
```

   ear signature
```{r, echo=FALSE}
heatmap.2(EAR_m_sorted, col=r, scale = "col", cexCol = 1, labRow = NA, key = TRUE, trace = "none", density.info = "none", dendrogram = "none", Rowv = "none", Colv = "none")
```
   
   LC signature
```{r, echo=FALSE}
heatmap.2(LC_m_sorted, col=r, scale = "col", cexCol = 1, labRow = NA, key = TRUE, trace = "none", density.info = "none", dendrogram = "none", Rowv = "none", Colv = "none")
```



```{r, include=FALSE}
## total gene clustering
t <- rbind.data.frame(DCT, EAR, LC)
t_m <- RNAseq(t)

corDist_total <- dist(t_m)

hCluCOM_total <-hclust(corDist_total, method = "complete")

cluCOM_dend_total <- as.dendrogram(hCluCOM_total)

```

### total h-Cluster heatmap
```{r, echo=FALSE}
heatmap.2(t_m, col=r, scale = "row", cexCol = 1, labRow = NA, key = TRUE, trace = "none", density.info = "none", dendrogram = "row", Rowv=cluCOM_dend_total)
```



```{r, include= FALSE}
'''
DCT_df <- as.data.frame(DCT_m)
GO_DCT <- as.factor(c(357:1))
GN_DCT <- DCT[1]
DCT_df <- cbind(DCT_df, GO_DCT, GN_DCT)
DCT_melt <- melt(DCT_df)

DCT_raw <- cbind(DCT, GO_DCT)
DCT_raw_melt <-melt(DCT_raw)

```

```{r, echo=FALSE}
ggplot(DCT_melt, aes(variable, GO_DCT)) +
  #heatmap은 tile형태로 그림. 
  geom_tile(aes(fill = value)) + 
  #heatmap용 gradient 먹이기.
  scale_fill_gradientn (colours = r) +
  #gene.order 숫자로 그린다음에 다시 gene name을 넣어줌.
  scale_y_discrete(breaks =NULL) +
  #x축 labeling없애기, legend 다 없애기.
  scale_x_discrete(breaks=NULL) + labs(x ="", y="")
+ theme(legend.position="none")

'''
```

